### ISSUE TITLE
optional query parameter specification

### ISSUE THREAD

**Issue by JoeCarlson** [earldouglas/swagger-test#24]
Thank you for providing swagger-test.
I had a problem with optional query parameters. I don't know if this is an issue of me not understanding x-amples well enough or a request for a new feature.
My endpoint is
`/api/call/{id}`
with 
```
...
  parameters:
  - name: id
    in: path
    required: true
  - name: option1
    in: query
    required: false
...
```

I'd like to execute my tests with and without option1. I hoped that an x-amples entry:
request:
```
...
           params:
             id: 123456
             option1: 10
...
```
would have generated `?option1=10` to the URL. But this is not the case and I don't see a mechanism for adding query parameters in url-template.js. Is there a mechanism for optional query parameters in swagger-test?
